version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.local
    container_name: twitter-trends-front.app
    volumes:
      - ./app:/app
    ports:
      - 3000:3000
    tty:
      true
